# Generated by Django 5.0 on 2023-12-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_Info_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_Number', models.CharField(max_length=100, null=True, unique=True)),
                ('CSTIN', models.CharField(blank=True, max_length=100, null=True)),
                ('GSTIN', models.CharField(blank=True, max_length=100, null=True)),
                ('State_Code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
