# Generated by Django 5.0 on 2023-12-08 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Designation', '__first__'),
        ('department', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.departmentu')),
                ('desig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Designation.designation')),
            ],
        ),
    ]
