# Generated by Django 5.0 on 2023-12-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_Info_Table',
            fields=[
                ('Invoice_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('CSTIN', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('State_Code', models.CharField(max_length=100)),
            ],
        ),
    ]
