# Generated by Django 5.0 on 2023-12-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
