# Generated by Django 5.0 on 2023-12-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_info_table',
            name='Invoice_Amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
