# Generated by Django 5.0 on 2023-12-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_info_table',
            name='Invoice_Number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
