# Generated by Django 5.0 on 2023-12-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='designation',
            fields=[
                ('designation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=100)),
            ],
        ),
    ]
