# Generated by Django 5.0 on 2023-12-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentu',
            old_name='department_name',
            new_name='department',
        ),
    ]
